# Generated by Django 4.2.6 on 2023-10-28 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('P', 'Petición'), ('Q', 'Queja'), ('R', 'Reclamo')], max_length=1)),
                ('descripcion', models.TextField()),
                ('fecha_hora_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Radicado', 'Radicado'), ('Asignado', 'Asignado'), ('En Trámite', 'En Trámite'), ('Cerrado', 'Cerrado')], default='Radicado', max_length=10)),
                ('fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('descripcion_cierre', models.TextField(blank=True, null=True)),
                ('comentario_asignacion', models.TextField(blank=True, null=True)),
                ('empleado_asignado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pqr_empleado', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqr_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionPQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('comentario_asignacion', models.TextField(blank=True, null=True)),
                ('empleado_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_pqr_empleado', to=settings.AUTH_USER_MODEL)),
                ('pqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peticiones.pqr')),
            ],
        ),
    ]
