# Generated by Django 4.2.6 on 2023-10-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='name_broker',
            field=models.CharField(default='MetaTrader', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='pass_server',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='server',
            field=models.CharField(max_length=20),
        ),
    ]
