# Generated by Django 4.2.6 on 2023-10-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_cuenta_name_broker_alter_cuenta_pass_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='name_broker',
            field=models.CharField(max_length=20),
        ),
    ]
