# Generated by Django 4.2.6 on 2023-10-15 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_estrategia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crear_Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estrategia', models.CharField(max_length=50)),
                ('divisa', models.CharField(max_length=10)),
                ('timeframe', models.CharField(choices=[('1M', '1 Minuto'), ('5M', '5 Minutos'), ('15M', '15 Minutos'), ('3M', '30 Minutos'), ('1H', '1 Hora'), ('4H', '4 Horas'), ('1D', '1 Día')], default='1D', max_length=3)),
                ('estado', models.BooleanField(default=False)),
                ('id_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuenta')),
                ('id_estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.estrategia')),
            ],
        ),
    ]
