# Generated by Django 4.2.6 on 2023-10-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_crear_estrategia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crear_estrategia',
            name='timeframe',
            field=models.CharField(choices=[('1M', '1 Minuto'), ('5M', '5 Minutos'), ('15M', '15 Minutos'), ('30M', '30 Minutos'), ('1H', '1 Hora'), ('4H', '4 Horas'), ('1D', '1 Día')], default='1D', max_length=3),
        ),
    ]
