# Generated by Django 4.2.6 on 2023-10-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_estrategia_codigo_python'),
    ]

    operations = [
        migrations.AddField(
            model_name='crear_estrategia',
            name='ultima_ejecucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
