# Generated by Django 4.2.6 on 2023-10-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='usuarios.role'),
        ),
    ]
